### ISSUE TITLE
Reading in fastq.gz files

### ISSUE THREAD

**Issue by waakanni** [ngless-toolkit/ngless2018benchmark#2]
NGLess `load_mocat_sample` does not ignore empty lines at the end of a fastq.gz file. Not sure if this is a bug or just something it was not meant to do

This is happening on both versions 1.0.1 and 0.7.1

error:

```
Exiting after fatal error while loading and running script
Data Error (the input data did not conform to ngless' expectations)
Number of input lines in FastQ file is not a multiple of 4

**Comment by luispedro** [comment]
Thanks for the report, but I am moving it to https://github.com/ngless-toolkit/ngless/issues/115 and answering there.
